name: Build Lytee ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y live-build git calamares zenity rofi feh mpv ffmpeg xserver-xorg-input-all

      - name: Build ISO
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: lytee-iso
          path: live-image-amd64.hybrid.iso
